# -*- coding: utf-8 -*-
"""Machine Learning Base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKGo1bvNq47Jk7oJAAZLXJrf3feT06F4
"""

import pandas as pd
data = pd.read_csv("exams.csv")

data

data.isna().sum()

data.dtypes

data['gender'].mode()

data['gender'].fillna('male', inplace=True)

data['math score'].mean()

data['math score'].fillna(66.38076152304609, inplace=True)

data['reading score'].mean()

data['reading score'].fillna(69.04828973843058 , inplace = True)

data['writing score'].mean()

data['writing score'].fillna(67.74474474474475 , inplace = True)

data.isna().sum()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data.dtypes

data['gender'] = le.fit_transform(data['gender'])

data['race/ethnicity'] = le.fit_transform(data['race/ethnicity'])

data['parental level of education'] = le.fit_transform(data['parental level of education'])

data['lunch'] = le.fit_transform(data['lunch'])

data['test preparation course'] = le.fit_transform(data['test preparation course'])

data['writing score'] = le.fit_transform(data['writing score'])

data.dtypes

data

from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = data.drop(columns = ['writing score'])
y = data['writing score']

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size = 0.25)

regressor = DecisionTreeRegressor(max_depth = 15, criterion='friedman_mse')

regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

y_test

y_pred

y

from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_pred)

print('R_Squared', r_squared )

from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test,y_pred)
rmse = mse ** 0.5
print("RMSE = ", rmse)

